require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.3  
  Exclude:
    - 'db/schema.rb'  
    - 'bin/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
  Max: 25  # ブロックの最大行数を25行に設定

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Enabled: true