name: Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: leaf_whisper
          POSTGRES_PASSWORD: pomchan1858
          POSTGRES_DB: leaf_whisper_test

    env:
      RAILS_ENV: test
      POSTGRES_USER: leaf_whisper
      POSTGRES_PASSWORD: pomchan1858
      POSTGRES_DB: leaf_whisper_test

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Ruby 3.3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.3

      - name: Setup bundler
        run: gem install bundler

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install gems
        run: bundle install --path vendor/bundle --jobs 4

      - name: Setup Database
        run: |
          cp -v config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run RSpec tests
        run: bundle exec rspec

      - name: Run RuboCop
        run: bundle exec rubocop