name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Rspec_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # スワップ領域を設定
      - name: Set up Swap (2GB)
        run: |
          sudo fallocate -l 2G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Check Memory Usage (Before Docker)
        run: free -m

      - name: Docker Stats (Before Docker)
        run: docker stats --no-stream
    
      - name: Set up Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.3

      - name: Set up docker
        shell: bash
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://leaf_whisper:pomchan1858@db:5432/leaf_whisper_development
        run: |
          docker compose up --build -d
          docker compose exec -T web bundle exec rails db:create
          docker compose exec -T web bundle exec rails db:migrate

      - name: RUN Rspec
        shell: bash
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://leaf_whisper:pomchan1858@db:5432/leaf_whisper_development
        run: |
          docker compose exec -T web bundle exec rspec --jobs 2

      # メモリ使用量を明示的にチェック
      - name: Check Memory Usage
        run: free -m

      # Dockerコンテナごとのメモリ使用量をモニタリング
      - name: Docker Stats
        run: docker stats --no-stream

      # RSpec実行後にカーネルログでOOM（メモリ不足）エラーを確認
      - name: Display Kernel Logs for OOM
        run: dmesg | grep -i 'out of memory' || echo "No OOM errors found"