name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Rspec_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # スワップ領域を4GBに設定
      - name: Set up Swap (4GB)
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Check Memory Usage (Before Docker)
        run: free -m

      - name: Docker Stats (Before Docker)
        run: docker stats --no-stream
    
      - name: Set up Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.3

      - name: Set up docker
        shell: bash
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://leaf_whisper:pomchan1858@db:5432/leaf_whisper_development
        run: |
          docker compose up --build -d
          docker compose exec -T web bundle exec rails db:create
          docker compose exec -T web bundle exec rails db:migrate

      - name: Check Memory Usage (Before RSpec)
        run: free -m

      # テストを分割して実行 (モデル)
      - name: RUN Rspec (Models)
        shell: bash
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://leaf_whisper:pomchan1858@db:5432/leaf_whisper_development
        run: |
          docker compose exec -T web bundle exec rspec --no-parallel spec/models

      # RSpec実行後にメモリ使用量をチェック
      - name: Check Memory Usage (After RSpec Models)
        run: free -m

      # テストを分割して実行 (コントローラー)
      - name: RUN Rspec (Controllers)
        shell: bash
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://leaf_whisper:pomchan1858@db:5432/leaf_whisper_development
        run: |
          docker compose exec -T web bundle exec rspec --no-parallel spec/controllers

      # RSpec実行後にメモリ使用量をチェック
      - name: Check Memory Usage (After RSpec Controllers)
        run: free -m

      # スワップ領域の使用状況を確認
      - name: Check Swap Usage
        run: swapon --show

      # Dockerコンテナごとのメモリ使用量をモニタリング
      - name: Docker Stats
        run: docker stats --no-stream

      # RSpec実行後にカーネルログでOOM（メモリ不足）エラーを確認
      - name: Display Kernel Logs for OOM
        run: dmesg | grep -i 'out of memory' || echo "No OOM errors found"